### ISSUE TITLE
Weblink for requirements to register NGO

### ISSUE THREAD

**Issue by Danie10** [opensourceza/saoss_constitution#1]
If @kmf can provide the correct link. It can go in Readme.md, and we can add the other required documents if needed in this repo.

**Comment by kmf** [comment]
@Danie10 We need to agree if this was the one?
https://www.gov.za/services/register-nonprofit-organisation

**Comment by Danie10** [comment]
Yes I'm pretty sure it was that one based on the three types including faith-based, and the reference to Social Development at the bottom. OK I'll go through it later, and add any other documents, and a summary to the readme.md, then I'll close this issue.

**Comment by Danie10** [comment]
OK all looks good. I have tweaked the readme.md to align with the requirements to register. A key aspect will be the Constitution addressing Section 12 requirements of the Act. So that will be our checklist. We need to address all relevant points in Section 12 otherwise the application may be rejected.
